[package]
name = "async_exercise"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.15"
async-std = { version = "1.2.0", features = ["attributes"] }
actix = "0.12"
